// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NameSearchCore;

namespace NameSearchCore.Migrations
{
    [DbContext(typeof(CommunityContext))]
    [Migration("20190502142108_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NameSearchCore.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "reading"
                        },
                        new
                        {
                            Id = 2,
                            Value = "watching movies"
                        },
                        new
                        {
                            Id = 3,
                            Value = "travelling"
                        },
                        new
                        {
                            Id = 4,
                            Value = "biking"
                        },
                        new
                        {
                            Id = 5,
                            Value = "running"
                        },
                        new
                        {
                            Id = 6,
                            Value = "gardening"
                        },
                        new
                        {
                            Id = 7,
                            Value = "shopping"
                        },
                        new
                        {
                            Id = 8,
                            Value = "boating"
                        },
                        new
                        {
                            Id = 9,
                            Value = "fishing"
                        },
                        new
                        {
                            Id = 10,
                            Value = "swimming"
                        });
                });

            modelBuilder.Entity("NameSearchCore.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PicturePath");

                    b.HasKey("Id");

                    b.ToTable("people");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Quiet Street",
                            Age = 30,
                            FirstName = "Henry",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1234 Noisy Street",
                            Age = 30,
                            FirstName = "Lisa",
                            LastName = "Rich"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1234 Normal Street",
                            Age = 30,
                            FirstName = "Emma",
                            LastName = "Moses"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1234 Main Street",
                            Age = 30,
                            FirstName = "Henry",
                            LastName = "Moor"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1234 State Street",
                            Age = 30,
                            FirstName = "Rich",
                            LastName = "Lisa"
                        },
                        new
                        {
                            Id = 6,
                            Address = "1234 Wall Street",
                            Age = 30,
                            FirstName = "John",
                            LastName = "Moor"
                        },
                        new
                        {
                            Id = 7,
                            Address = "1234 Spring Street",
                            Age = 30,
                            FirstName = "Mark",
                            LastName = "Dean"
                        },
                        new
                        {
                            Id = 8,
                            Address = "1234 Summer Street",
                            Age = 30,
                            FirstName = "Rob",
                            LastName = "Henderson"
                        },
                        new
                        {
                            Id = 9,
                            Address = "1234 Fall Street",
                            Age = 30,
                            FirstName = "Tiffany",
                            LastName = "Locante"
                        },
                        new
                        {
                            Id = 10,
                            Address = "1234 Winter Street",
                            Age = 30,
                            FirstName = "Laura",
                            LastName = "Carrell"
                        });
                });

            modelBuilder.Entity("NameSearchCore.PersonInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("InterestId");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PeopleInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 3,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 4,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 4,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 5,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 9,
                            InterestId = 5,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 10,
                            InterestId = 6,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 11,
                            InterestId = 6,
                            PersonId = 6
                        },
                        new
                        {
                            Id = 12,
                            InterestId = 7,
                            PersonId = 6
                        },
                        new
                        {
                            Id = 13,
                            InterestId = 7,
                            PersonId = 7
                        },
                        new
                        {
                            Id = 14,
                            InterestId = 8,
                            PersonId = 7
                        },
                        new
                        {
                            Id = 15,
                            InterestId = 8,
                            PersonId = 8
                        },
                        new
                        {
                            Id = 16,
                            InterestId = 9,
                            PersonId = 8
                        },
                        new
                        {
                            Id = 17,
                            InterestId = 9,
                            PersonId = 9
                        },
                        new
                        {
                            Id = 18,
                            InterestId = 10,
                            PersonId = 9
                        },
                        new
                        {
                            Id = 19,
                            InterestId = 10,
                            PersonId = 10
                        },
                        new
                        {
                            Id = 20,
                            InterestId = 1,
                            PersonId = 10
                        });
                });

            modelBuilder.Entity("NameSearchCore.PersonInterest", b =>
                {
                    b.HasOne("NameSearchCore.Interest", "Interest")
                        .WithMany("PeopleInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NameSearchCore.Person", "person")
                        .WithMany("PeopleInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
