// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NameSearchCore;

namespace NameSearchCore.Migrations
{
    [DbContext(typeof(CommunityContext))]
    partial class CommunityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NameSearchCore.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonId = 1,
                            Value = "reading"
                        },
                        new
                        {
                            Id = 2,
                            PersonId = 2,
                            Value = "watching movies"
                        },
                        new
                        {
                            Id = 3,
                            PersonId = 3,
                            Value = "travelling"
                        },
                        new
                        {
                            Id = 4,
                            PersonId = 4,
                            Value = "biking"
                        },
                        new
                        {
                            Id = 5,
                            PersonId = 5,
                            Value = "running"
                        },
                        new
                        {
                            Id = 6,
                            PersonId = 6,
                            Value = "do nothing"
                        },
                        new
                        {
                            Id = 7,
                            PersonId = 6,
                            Value = "reading"
                        },
                        new
                        {
                            Id = 8,
                            PersonId = 5,
                            Value = "watching movies"
                        },
                        new
                        {
                            Id = 9,
                            PersonId = 4,
                            Value = "travelling"
                        },
                        new
                        {
                            Id = 10,
                            PersonId = 3,
                            Value = "biking"
                        },
                        new
                        {
                            Id = 11,
                            PersonId = 2,
                            Value = "running"
                        },
                        new
                        {
                            Id = 12,
                            PersonId = 1,
                            Value = "do nothing"
                        });
                });

            modelBuilder.Entity("NameSearchCore.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PicturePath");

                    b.HasKey("Id");

                    b.ToTable("people");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Quiet Street",
                            Age = 30,
                            FirstName = "Henry",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1234 Noisy Street",
                            Age = 30,
                            FirstName = "Lisa",
                            LastName = "Rich"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1234 Normal Street",
                            Age = 30,
                            FirstName = "Emma",
                            LastName = "Moses"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1234 Main Street",
                            Age = 30,
                            FirstName = "Henry",
                            LastName = "Moor"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1234 State Street",
                            Age = 30,
                            FirstName = "Rich",
                            LastName = "Lisa"
                        },
                        new
                        {
                            Id = 6,
                            Address = "1234 Wall Street",
                            Age = 30,
                            FirstName = "John",
                            LastName = "Moor"
                        });
                });

            modelBuilder.Entity("NameSearchCore.Interest", b =>
                {
                    b.HasOne("NameSearchCore.Person", "Person")
                        .WithMany("Interests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
